### PR TITLE
Add lpha blog post

### PR DESCRIPTION
**Pull request by lars-petter-hauge**
Do you have any suggestions for the tags?

I haven't added any image yet, unsure if that is required/desired?

### CODE REVIEW

**Comment by lars-petter-hauge** [comment]
Managed to put the PR on develop branch, closed that one and created this instead.

The `equinor:lpha_blog_exchange` should be deleted

**Comment by cbuv** [comment]
Pull requests should target the develop branch, and normally hotfixes or new releases from develop is merged to master.

**Comment by cbuv** [comment]
I´ve changed target branch to develop, which is the workflow.

The following need to be addressed before merging:
1. Date format must be on the format YYYY-MM-DD
2. A valid github username must be used in author
3. tags must have one or more values. eg "Software Innovation",  "FMU", "ERT"

**Comment by lars-petter-hauge** [comment]
Wasn't sure which branch you wanted it on, thanks for fixing it.

Updated the PR now with the requested changes.

**Comment by cbuv** [comment]
date still needs to be YYYY-mm-DD, see other blog posts

**Comment by lars-petter-hauge** [comment]
Fixed the date format and rebased on develop branch

**Pull request merged**
